name: Scarf Hello-World presentation

on:
  push:
    branches: [ "feature/devops-test-execution-1" ]
  pull_request:
    branches: [ "feature/devops-test-execution-1" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the scarf-test Docker image
      run:  cd ./src && docker build --tag scarf-test:latest .

    - name: Creating "kind" cluster and deploying hello-world app 
      run: ./.github/scripts/deploy.sh
      shell: bash