name: Scarf Hello-World presentation

on:
  push:
    branches: [ "feature/devops-test-execution-1" ]
  pull_request:
    branches: [ "feature/devops-test-execution-1" ]

jobs:
  scarf-devops-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Building "hello-world" Docker image, creating "kind" cluster and deploying app
      run: ./.github/scripts/deploy.sh
      shell: bash